### ISSUE TITLE
Attestation with GrapheneOS Auditor App

### ISSUE THREAD

**Issue by attisimon** [Divested-Mobile/DivestOS-Build#317] opened 2024-07-08 09:51 UTC
Hello!

Out of curiosity, I tried to use the GrapheneOS Auditor App with DivestOS, but it does not work at all. 

The following issue discussed the problem, as it seems, some key fingerprints of supported devices need to be added on GrapheneOS' side:
https://github.com/GrapheneOS/Auditor/issues/272

Would this something doable?

I'm only guessing here, but if this will be done, remote attestation would also be possible, an important option for those interested in this.

Thanks!

**Comment by SkewedZeppelin** [comment] 2024-07-08 11:41
Duplicate of https://github.com/Divested-Mobile/DivestOS-Build/discussions/46

**Closed by SkewedZeppelin** 2024-07-08 11:41 UTC
