### ISSUE TITLE
Bluetooth doesn't work on thor

### ISSUE THREAD

**Issue by CaioCesarPM** [Divested-Mobile/DivestOS-Build#16] opened 2021-10-06 07:03 UTC
I have installed DivestOS from scratch on my Fire HDX 7 32GB but when I try to enable Bluetooth (using either the notification bar or settings) it asks for permission. After allowing, an error message appears constantly on the screen, no matter how often I dismiss it. Only restarting makes it stop (bluetooth remains disabled).

![Screenshot_20211006-155216](https://user-images.githubusercontent.com/47683070/136155330-94827efb-3bdb-4ed2-b00b-7bf0878cabbd.png)

I have wiped everything using TWRP 3.5.0_9-1 and installed divested-14.1-20211002-dos-thor.zip (though this happened with previous versions too).

This problem doesn't happen when using the LineageOS builds on XDA forums (either 14.1 or 16.0).
The [logcat.txt](https://github.com/Divested-Mobile/DivestOS-Build/files/7291502/logcat.txt) also shows a ton of error messages after trying to enable Bluetooth.

**Comment by SkewedZeppelin** [comment] 2021-10-06 08:24
That appears to be caused by https://review.lineageos.org/c/LineageOS/android_system_bt/+/249553, but the crashing was fixed in https://review.lineageos.org/c/LineageOS/android_system_bt/+/252935.

You say LineageOS 14.1 from XDA worked, but how old is that build?

**Comment by CaioCesarPM** [comment] 2021-10-06 08:35
> You say LineageOS 14.1 from XDA worked, but how old is that build?
I used lineage-14.1-20200705-UNOFFICIAL-thor

**Closed** 2021-10-06 08:53 UTC
Labels: bug

**Comment by SkewedZeppelin** [comment] 2021-10-06 08:55
I have likely fixed this issue, builds will be up within the next few days.

**Comment by SkewedZeppelin** [comment] 2021-10-06 10:24
A new build is up, please test.

**Comment by CaioCesarPM** [comment] 2021-10-06 15:12
Thanks!
I just tested with a mouse and it worked fine.
My earphones, however, never seem to finish pairing but I guess that's Sony's fault.

**Comment by CaioCesarPM** [comment] 2021-10-07 02:29
Update: sorry, apparently my earphones stopped pairing on LineageOS [too](https://github.com/Divested-Mobile/DivestOS-Build/files/7298272/logcat.txt). Maybe my Kindle doesn't like them?
